require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MemberOnCloud' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera/Permission-Camera.podspec"

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'MemberOnCloudTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MemberOnCloud-tvOS' do
  # Pods for MemberOnCloud-tvOS

  target 'MemberOnCloud-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
